# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c94dd0452fcf20eec285e75b0d20ac751fe75ce2480d0e3e2d01924d7201f9240156391f328be498c1b5aa5275fb44066f3ddc1245d78cdf37bd64767114e5

test:
  secret_key_base: 352f3953e2f9577d317f4ce55331e889c0a263c527f5ba29efaf69231412f0434ce47808eb7db7bb3d2137477fd12e5e8b96c098f56c3a85cb73c2b956ca7e7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
